services:
  - type: web
    name: udaan-backend
    runtime: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: cd Udaan2/Student_helper_2\ 3/Backend/app && pip install -r ../requirements.txt
    startCommand: sh start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FRONTEND_URL
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_ENDPOINT
        value: "https://api.smith.langchain.com"
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: "Chat_bot_usage"
